apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sampleapp
  namespace: prometheus
  labels:
    release: sampleapp
spec:
  selector:
    matchLabels:
      app: sampleapp
  endpoints:
  - port: metrics
